const OVERPASS_URL = 'https://overpass-api.de/api/interpreter';

// SF bounding box: south, west, north, east
const SF_BBOX = '37.7081,-122.5155,37.8124,-122.3531';

const CACHE_TTL = 6 * 60 * 60 * 1000; // 6 hours in milliseconds

/**
 * Reads a JSON array from localStorage, returning null if the entry is
 * missing, expired, or fails a basic shape check (`{ts, data[]}`) that
 * guards against tampered or structurally unexpected cache entries.
 *
 * @param {string} key
 * @returns {Array|null}
 */
function readCache(key) {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    // Validate shape before trusting cached data
    if (typeof parsed?.ts !== 'number' || !Array.isArray(parsed?.data)) return null;
    if (Date.now() - parsed.ts > CACHE_TTL) return null;
    return parsed.data;
  } catch (_) {
    return null;
  }
}

/**
 * Writes a JSON value to localStorage with the current timestamp.
 * Silently ignores QuotaExceededError and other storage errors.
 *
 * @param {string} key
 * @param {any} data
 */
function writeCache(key, data) {
  try {
    localStorage.setItem(key, JSON.stringify({ ts: Date.now(), data }));
  } catch (_) {
    // Silently ignore QuotaExceededError and other storage errors
  }
}

/**
 * Sends an Overpass QL query and returns the parsed JSON response.
 * Retries once after a 1-second delay on network or HTTP errors.
 *
 * @param {string} query - Overpass QL query string.
 * @param {number} [retries=1] - Number of retry attempts remaining.
 * @returns {Promise<Object>} Parsed Overpass JSON response.
 * @throws {Error} If all retry attempts fail.
 */
async function overpassQuery(query, retries = 1) {
  try {
    const res = await fetch(OVERPASS_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: `data=${encodeURIComponent(query)}`,
    });
    if (!res.ok) throw new Error(`Overpass error: ${res.status}`);
    return res.json();
  } catch (err) {
    if (retries > 0) {
      await new Promise(resolve => setTimeout(resolve, 1000));
      return overpassQuery(query, retries - 1);
    }
    throw err;
  }
}

/**
 * Normalises a raw Overpass element into a venue object.
 *
 * Handles both node elements (have `lat`/`lon` directly) and way elements
 * (have a `center` object from `out center`).
 *
 * @param {Object} el - Raw Overpass element.
 * @param {'venue'|'park'} type - Logical type to assign.
 * @returns {{
 *   id: number, lat: number, lng: number,
 *   name: string, amenity: string, type: string,
 *   outdoorSeating: boolean, cuisine: string|null,
 *   website: string|null, address: string|null
 * }|null} Normalised venue, or null if coordinates are missing.
 */
function parseElement(el, type) {
  const lat = el.lat ?? el.center?.lat;
  const lng = el.lon ?? el.center?.lon;
  if (!lat || !lng) return null;

  const isGreenSpace = type === 'park';
  const greenLabel =
    el.tags?.leisure === 'viewpoint' ? 'viewpoint' :
    el.tags?.natural === 'peak'      ? 'peak' :
    el.tags?.leisure === 'garden'    ? 'garden' :
    'park';

  return {
    id: el.id,
    lat,
    lng,
    name: el.tags?.name || greenLabel,
    amenity: isGreenSpace ? greenLabel : el.tags?.amenity,
    type,
    outdoorSeating: isGreenSpace || el.tags?.outdoor_seating === 'yes',
    cuisine: el.tags?.cuisine || null,
    website: el.tags?.website || el.tags?.['contact:website'] || null,
    address: el.tags?.['addr:street']
      ? `${el.tags?.['addr:housenumber'] || ''} ${el.tags?.['addr:street']}`.trim()
      : null,
  };
}

/**
 * Fetches all scoreable venues within SF: cafes, restaurants, bars, parks,
 * viewpoints, gardens, and named peaks.
 *
 * Strategy (in priority order):
 * 1. Static bundled file at `/data/venues.json` — served from CDN in production,
 *    zero latency and no rate-limit risk. Generated by `npm run fetch-data`.
 * 2. localStorage cache (6-hour TTL) — avoids repeat Overpass hits during dev.
 * 3. Live Overpass API — fallback when neither of the above is available.
 *
 * @returns {Promise<Array<{
 *   id: number, lat: number, lng: number,
 *   name: string, amenity: string, type: 'venue'|'park',
 *   outdoorSeating: boolean, cuisine: string|null,
 *   website: string|null, address: string|null
 * }>>}
 */
export async function fetchVenues() {
  // 1. Static bundle
  try {
    const res = await fetch('/data/venues.json');
    if (res.ok) return res.json();
  } catch (_) {}

  // 2. localStorage cache
  const cached = readCache('sf_venues_v1');
  if (cached) return cached;

  // 3. Live Overpass
  const venueQuery = `
    [out:json][timeout:35];
    node["amenity"~"^(cafe|restaurant|bar)$"]["name"](${SF_BBOX});
    out body 600;
  `;
  const parkQuery = `
    [out:json][timeout:35];
    (
      node["leisure"~"^(park|viewpoint|garden)$"](${SF_BBOX});
      way["leisure"~"^(park|garden)$"](${SF_BBOX});
      node["natural"="peak"]["name"](${SF_BBOX});
    );
    out body center 500;
  `;

  const [venueData, parkData] = await Promise.all([
    overpassQuery(venueQuery),
    overpassQuery(parkQuery),
  ]);

  const seen = new Set();
  const results = [];

  for (const el of venueData.elements) {
    const item = parseElement(el, 'venue');
    if (!item) continue;
    const key = `${item.lat.toFixed(4)}_${item.lng.toFixed(4)}`;
    if (seen.has(key)) continue;
    seen.add(key);
    results.push(item);
  }

  for (const el of parkData.elements) {
    const item = parseElement(el, 'park');
    if (!item) continue;
    const key = `${item.lat.toFixed(4)}_${item.lng.toFixed(4)}`;
    if (seen.has(key)) continue;
    seen.add(key);
    results.push(item);
  }

  writeCache('sf_venues_v1', results);
  return results;
}

/**
 * Fetches tall building polygons (3+ stories or height ≥ 20 m) within SF
 * as GeoJSON Feature objects ready for use with `prepareBuildingIndex()`.
 *
 * Strategy (in priority order):
 * 1. Static bundled file at `/data/buildings.json` — served from CDN.
 * 2. localStorage cache (6-hour TTL).
 * 3. Live Overpass API fallback.
 *
 * Building height is derived from `building:levels` (× 3.5 m per floor)
 * when an explicit `height` tag is absent.
 *
 * @returns {Promise<Array<GeoJSON.Feature<GeoJSON.Polygon, { height: number }>>>}
 */
export async function fetchTallBuildings() {
  // 1. Static bundle
  try {
    const res = await fetch('/data/buildings.json');
    if (res.ok) return res.json();
  } catch (_) {}

  // 2. localStorage cache
  const cached = readCache('sf_buildings_v2');
  if (cached) return cached;

  // 3. Live Overpass
  const query = `
    [out:json][timeout:60];
    (
      way["building"]["building:levels"~"^([3-9]|[1-9][0-9]+)$"](${SF_BBOX});
      way["building"]["height"~"^([2-9][0-9]|[1-9][0-9]{2,})(\\..*)?$"](${SF_BBOX});
    );
    out geom;
  `;
  const data = await overpassQuery(query);

  const features = [];
  for (const el of data.elements) {
    if (!el.geometry || el.geometry.length < 3) continue;
    const coords = el.geometry.map(pt => [pt.lon, pt.lat]);
    const first = coords[0], last = coords[coords.length - 1];
    if (first[0] !== last[0] || first[1] !== last[1]) coords.push(first);

    const levels = parseInt(el.tags?.['building:levels']) || null;
    const heightRaw = el.tags?.height;
    const height = heightRaw ? parseFloat(heightRaw) : levels ? levels * 3.5 : 14;

    features.push({
      type: 'Feature',
      geometry: { type: 'Polygon', coordinates: [coords] },
      properties: { height },
    });
  }

  writeCache('sf_buildings_v2', features);
  return features;
}
